language: elixir

elixir:
    - 1.6.6
    - 1.7.1

otp_release:
    - 20.3
    - 21.0

script:
    - mix compile --warnings-as-errors
    - mix test
    - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
